-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.document
(
    doc_id integer NOT NULL,
    sign_date timestamp without time zone NOT NULL,
    doc_type character varying NOT NULL,
    didgitalization boolean NOT NULL DEFAULT false,
    archive_id integer NOT NULL,
    PRIMARY KEY (doc_id)
);

CREATE TABLE IF NOT EXISTS public.archive
(
    archive_id integer NOT NULL,
    adress character varying NOT NULL,
    public_state boolean NOT NULL DEFAULT true,
    ownership character varying NOT NULL,
    PRIMARY KEY (archive_id)
);

CREATE TABLE IF NOT EXISTS public.signer
(
    signer_id integer NOT NULL,
    fullname character varying NOT NULL,
    signer_role character varying NOT NULL,
    PRIMARY KEY (signer_id)
);

CREATE TABLE IF NOT EXISTS public.signer_document
(
    signer_signer_id integer NOT NULL,
    document_doc_id integer NOT NULL
);

ALTER TABLE IF EXISTS public.document
    ADD FOREIGN KEY (archive_id)
    REFERENCES public.archive (archive_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.signer_document
    ADD FOREIGN KEY (signer_signer_id)
    REFERENCES public.signer (signer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.signer_document
    ADD FOREIGN KEY (document_doc_id)
    REFERENCES public.document (doc_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;